services:
  tuwunel:
    image: jevolk/tuwunel@sha256:25693407bc059eec7e161418edd02b2b7c010516c855056a7672883b04f71b11
    restart: unless-stopped
    labels:
      - "git.sha=${GIT_SHA}"
    volumes:
      - tuwunel-data:/var/lib/tuwunel
      - ./tuwunel/tuwunel.toml:/etc/tuwunel/tuwunel.toml:ro
    environment:
      TUWUNEL_CONFIG: /etc/tuwunel/tuwunel.toml
      # Manual registration enable
      # echo "REGISTRATION_TOKEN=$(head -c 64 /dev/urandom | base64 -w 0)" > /opt/matrix/.env
      # TUWUNEL_REGISTRATION_TOKEN: ${REGISTRATION_TOKEN}
    networks:
      - internal

  caddy:
    image: caddy@sha256:a1b7e624f860619cea121bdbc5dec2e112401666298c6507c6793b0a3ee6fc8e
    restart: unless-stopped
    environment:
      GIT_SHA: ${GIT_SHA}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - internal

volumes:
  tuwunel-data:
  caddy-data:
  caddy-config:

networks:
  internal:
