services:
  tuwunel:
    image: jevolk/tuwunel@sha256:25693407bc059eec7e161418edd02b2b7c010516c855056a7672883b04f71b11
    restart: unless-stopped
    labels:
      - "git.sha=${GIT_SHA}"
    volumes:
      - tuwunel-data:/var/lib/tuwunel
      - ./tuwunel/tuwunel.toml:/etc/tuwunel/tuwunel.toml:ro
    environment:
      TUWUNEL_CONFIG: /etc/tuwunel/tuwunel.toml
      TUWUNEL_TURN_SECRET: ${COTURN_SECRET}
      # Manual registration enable
      # echo "REGISTRATION_TOKEN=$(head -c 64 /dev/urandom | base64 -w 0)" > /opt/matrix/.env
      # TUWUNEL_REGISTRATION_TOKEN: ${REGISTRATION_TOKEN}
    networks:
      - internal

  livekit:
    image: livekit/livekit-server:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./livekit/livekit.yaml:/etc/livekit.yaml:ro
    command: --config /etc/livekit.yaml --node-ip=${EXTERNAL_IP}
    environment:
      LIVEKIT_KEYS: "${LIVEKIT_KEY}: ${LIVEKIT_SECRET}"

  lk-jwt-service:
    image: ghcr.io/element-hq/lk-jwt-service:latest
    restart: unless-stopped
    environment:
      LIVEKIT_URL: wss://livekit.corytodd.us
      LIVEKIT_KEY: ${LIVEKIT_KEY}
      LIVEKIT_SECRET: ${LIVEKIT_SECRET}
      LIVEKIT_FULL_ACCESS_HOMESERVERS: corytodd.us
    networks:
      - internal

  coturn:
    image: coturn/coturn:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./coturn/turnserver.conf:/etc/coturn/turnserver.conf:ro
    command: -c /etc/coturn/turnserver.conf --static-auth-secret=${COTURN_SECRET} --external-ip=${EXTERNAL_IP}

  caddy:
    image: caddy@sha256:a1b7e624f860619cea121bdbc5dec2e112401666298c6507c6793b0a3ee6fc8e
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      GIT_SHA: ${GIT_SHA}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - internal

volumes:
  tuwunel-data:
  caddy-data:
  caddy-config:

networks:
  internal:
