[global]
server_name = "corytodd.us"
database_path = "/var/lib/tuwunel/db"
port = [6167]
address = ["0.0.0.0"]

allow_registration = false
allow_federation = true

new_user_displayname_suffix = ""

# Hardening
allow_inbound_profile_lookup_federation_requests = false
allow_device_name_federation = false
encryption_enabled_by_default_for_room_type = "all"

max_request_size = 20_000_000

# TURN server for audio/video calls
turn_uris = [
  "turn:turn.corytodd.us:3478?transport=udp",
  "turn:turn.corytodd.us:3478?transport=tcp",
]
turn_ttl = 86400

trusted_servers = ["matrix.org"]
